version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db_project
      POSTGRES_USER: root
      POSTGRES_PASSWORD: my_password
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    links:
      - redis:cache

  api:
    image: dev_server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
      - ./logs/web:/logs
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env
      - .env.docker
    environment:
      - BROKER_URL=redis://cache
      - MEDIA_ROOT=/media
      - LOGS_ROOT=/logs
    links:
      - redis:cache

  worker:
    image: dev_worker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
      - ./logs/worker:/logs
      - ./media
    command: python manage.py celery
    env_file:
      - .env
      - .env.docker
    environment:
      - BROKER_URL=redis://cache
      - MEDIA_ROOT=/media
      - LOGS_ROOT=/logs
    links:
      - redis:cache

  redis:
    image: redis
    expose:
      - 6379

volumes:
  db:
